In [14]:
import numpy
import cv2

In [2]:
n = numpy.arange(27)

In [3]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [4]:
n.reshape(3,9)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8],
       [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25, 26]])

In [5]:
n

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [6]:
n.reshape(3,3,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [7]:
#convert python list to numpy array

In [8]:
[[123,12,123,13,33], [], []] #python list

[[123, 12, 123, 13, 33], [], []]

In [ ]:
#numpy arrays out of images

In [12]:
m = numpy.asarray([[123,12,123,13,33], [], []])

In [13]:
m

array([list([123, 12, 123, 13, 33]), list([]), list([])], dtype=object)

In [25]:
im_g1 = cv2.imread("smallgray.png", 0)   #0 for greyscale, 1 for bgr

In [26]:
im_g1

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [19]:
im_g = cv2.imread("smallgray.png", 1)

In [20]:
im_g    #here it shows transpose, its actually a row matrix not a column matrix

array([[[187, 187, 187],
        [158, 158, 158],
        [104, 104, 104],
        [121, 121, 121],
        [143, 143, 143]],

       [[198, 198, 198],
        [125, 125, 125],
        [255, 255, 255],
        [255, 255, 255],
        [147, 147, 147]],

       [[209, 209, 209],
        [134, 134, 134],
        [255, 255, 255],
        [ 97,  97,  97],
        [182, 182, 182]]], dtype=uint8)

In [21]:
#create images out of numpy array

In [22]:
cv2.imwrite("newsmallgray.png", im_g)

True

In [27]:
im_g1

array([[187, 158, 104, 121, 143],
       [198, 125, 255, 255, 147],
       [209, 134, 255,  97, 182]], dtype=uint8)

In [28]:
#you want 104, 121, 255, 255

In [29]:
im_g1[0:2,2:4]   #rememeber range is upper limit exclusive

array([[104, 121],
       [255, 255]], dtype=uint8)